version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: modeweb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modeweb
    ports:
      - "5432:5432"
    volumes:
      - modeweb_postgres_data:/var/lib/postgresql/data

volumes:
  modeweb_postgres_data:
